### ISSUE TITLE
Crash of boinc-manager upon selection of notices tab with no/bad internet connection

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1157]
**Reported by smoe on 6 Feb 42407923 03:06 UTC**
Hello,

I am reporting a crash that is nicely reproducible running boinc client 7.0.28: Try "ifdown eth0" or something else to stop your internet to work, start boincmgr and select the "Notices" tab. Segfault. The CmpNoCase I presume to be called with a NULL argument, wildly guessing.

When running BOINC on some mobile computer, one is rather likely to experience this problem. Otherwise, well, ... I kindly ask to have a look through those parts anyway since sometimes the BOINC manager just hangs when selecting that tab. But that I could not reliably reproduce that.

Thanks

Steffen

[run[[BR]([BR]](gdb))]Starting program: /usr/bin/boincmgr [debugging using libthread_db enabled]([BR]][Thread)[host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".[[BR]([BR]]Using)][Thread 0x7fffee1e3700 (LWP 5637)](New)[--redirectio, --launched_by_manager) failed with error 2! [[BR]([BR]]execvp(/home/moeller/boinc,)]execvp(/home/moeller/boinc, --redirectio, --launched_by_manager) failed with error 2! [received signal SIGSEGV, Segmentation fault.[[BR]([BR]][[BR]]Program)]0x00007ffff6961c61 in wxString::!CmpNoCase(wchar_t const*) const () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[bt[[BR]([BR]](gdb))]!#0 0x00007ffff6961c61 in wxString::!CmpNoCase(wchar_t const*) const () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[0x00007ffff69636c5 in wxArrayString::Index(wchar_t const*, bool, bool) const () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[[BR]([BR]]!#1)]!#2 0x00007ffff7793a44 in wxHtmlTag::!HasParam(wxString const&) const () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[0x00007ffff77a37fe in wxHTML_Handler_IMG::!HandleTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[[BR]([BR]]!#3)]!#4 0x00007ffff779253d in wxHtmlParser::!AddTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[0x00007ffff7792356 in wxHtmlParser::!DoParsing(int, int) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[[BR]([BR]]!#5)]!#6 0x00007ffff77a658b in wxHTML_Handler_A::!HandleTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[0x00007ffff779253d in wxHtmlParser::!AddTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[[BR]([BR]]!#7)]!#8 0x00007ffff7792356 in wxHtmlParser::!DoParsing(int, int) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[0x00007ffff77ab319 in wxHTML_Handler_TABLE::!HandleTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[[BR]([BR]]!#9)]!#10 0x00007ffff779253d in wxHtmlParser::!AddTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[0x00007ffff7792356 in wxHtmlParser::!DoParsing(int, int) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[[BR]([BR]]!#11)]!#12 0x00007ffff779258a in wxHtmlParser::!AddTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[0x00007ffff7792356 in wxHtmlParser::!DoParsing(int, int) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[[BR]([BR]]!#13)]!#14 0x00007ffff77ab090 in wxHTML_Handler_TABLE::!HandleTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[0x00007ffff779253d in wxHtmlParser::!AddTag(wxHtmlTag const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[[BR]([BR]]!#15)]!#16 0x00007ffff7792356 in wxHtmlParser::!DoParsing(int, int) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[0x00007ffff779262f in wxHtmlParser::Parse(wxString const&) () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_html-2.8.so.0[[BR]([BR]]!#17)]!#18 0x000000000045c3e5 in CBOINCHtmlListBox::!CacheItem (this=this@entry=0x966760, n=n@entry=0) at !BOINCHtmlLBox.cpp:285 [0x000000000045c65b in CBOINCHtmlListBox::!GetMaxItemWidth (this=0x966760) at !BOINCHtmlLBox.cpp:383 [[BR]([BR]]!#19)]!#20 0x00000000004639d6 in CBOINCVListBox::!UpdateScrollbar (this=0x966760) at !BOINCVListBox.cpp:115 [0x0000000000498640 in CNoticeListCtrl::UpdateUI (this=0x966760) at !NoticeListCtrl.cpp:573 [[BR]([BR]]!#21)]!#22 0x00000000004cb856 in CViewNotices::!OnListRender (this=0x964600) at !ViewNotices.cpp:133 [0x00000000004470af in CAdvancedFrame::!OnRefreshView (this=0x8b9400) at !AdvancedFrame.cpp:1611 [[BR]([BR]]!#23)]!#24 0x00007ffff6994275 in wxEvtHandler::!ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()[from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[[BR]([BR]])]!#25 0x00007ffff69943dc in wxEventHashTable::!HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[0x00007ffff6994714 in wxEvtHandler::!ProcessEvent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[[BR]([BR]]!#26)]!#27 0x000000000044a10d in CMainDocument::HandleCompletedRPC (this=0x8c6800) at !AsyncRPC.cpp:1141 [0x00007ffff6994275 in wxEvtHandler::!ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()[[BR]([BR]]!#28)] from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[0x00007ffff69943dc in wxEventHashTable::!HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[[BR]([BR]]!#29)]!#30 0x00007ffff6994714 in wxEvtHandler::!ProcessEvent(wxEvent&) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[0x00007ffff69941e0 in wxEvtHandler::!ProcessPendingEvents() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[[BR]([BR]]!#31)]!#32 0x00007ffff6916169 in wxAppConsole::!ProcessPendingEvents() () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[0x00007ffff70aca09 in wxAppBase::!ProcessIdle() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0[[BR]([BR]]!#33)]!#34 0x00007ffff70219dd in ?? () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0[0x00007ffff56a0205 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0[[BR]([BR]]!#35)]!#36 0x00007ffff56a0538 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0[0x00007ffff56a0932 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0[[BR]([BR]]!#37)]!#38 0x00007ffff5cdaa77 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0[0x00007ffff7035698 in wxEventLoop::Run() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0[[BR]([BR]]!#39)]!#40 0x00007ffff70ac82b in wxAppBase::!MainLoop() () from /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-2.8.so.0[0x00007ffff694561b in wxEntry(int&, wchar_t**) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0[[BR]([BR]]!#41)]!#42 0x000000000042c8a2 in main (argc=1, argv=<optimized out>) at !BOINCGUIApp.cpp:59 [[BR]](gdb)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1185

**Comment by romw** [comment]
**Commented by Trog Dog on 12 Jun 42409338 11:56 UTC**

```
I kindly ask to have a look through those parts anyway since sometimes the BOINC manager just hangs when selecting that tab. But that I could not reliably reproduce that.
```

Also reported in ticket 1184
