### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1199]
**Reported by amine548 on 27 May 43183788 22:38 UTC**
==== Comment reproduire ====

En excutant une opration GET sur `/query`, Trac a lev une erreur interne.

''(merci de fournir de plus amples dtails ici)''

Paramtres de la requte:

```
{'group': u'status',
 'milestone': u'Undetermined',
 'status': [u'new', u'reopened'](u'assigned',)}
```

User agent: `#USER_AGENT#`

==== Information systme ====
''Information systme non disponible''

==== Extensions actives ====
''Information sur les extensions non disponible''

==== Pile d'appel Python ====

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trac/web/main.py", line 522, in _dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.7/site-packages/trac/web/main.py", line 266, in dispatch
    req.session.save()
  File "/usr/lib/python2.7/site-packages/trac/web/session.py", line 105, in save
    @self.env.with_transaction()
  File "/usr/lib/python2.7/site-packages/trac/db/api.py", line 77, in transaction_wrapper
    fn(ldb)
  File "/usr/lib/python2.7/site-packages/trac/web/session.py", line 140, in save_session
    """, (self.sid, authenticated))
  File "/usr/lib/python2.7/site-packages/trac/db/util.py", line 65, in execute
    return self.cursor.execute(sql_escape_percent(sql), args)
  File "/usr/lib/python2.7/site-packages/trac/db/sqlite_backend.py", line 78, in execute
    result = PyFormatCursor.execute(self, *args)
  File "/usr/lib/python2.7/site-packages/trac/db/sqlite_backend.py", line 56, in execute
    args or [])
  File "/usr/lib/python2.7/site-packages/trac/db/sqlite_backend.py", line 48, in _rollback_on_error
    return function(self, *args, **kwargs)
OperationalError: database is locked
```

**Comment by romw** [comment]
**Commented by ChristianB on 26 Mar 43183837 15:12 UTC**
This was just a trac/database hiccup. The query works again.
