### ISSUE TITLE
./make_project mysql error 1072

### ISSUE THREAD

**Issue by tanorjb** [BOINC/boinc#1807]
Looking to set up a BOINC server for a class project and am running into an issue when I attempt to use make_project to make cplan for testing. OS: Debian 8
---------------------------------------------------------------------------------------------------------------------------------
boincadmin@BOINCServer:~/boinc-src/tools$ ./make_project --delete_prev_inst --drop_db_first --db_user root --db_passwd root --test_app cplan
Creating project 'cplan' (short name 'cplan'):
   PROJECT_ROOT = /home/boincadmin/projects/cplan/
   PROJECT_HOST = BOINCServer
       URL_BASE = http://BOINCServer/
  HTML_USER_URL = http://BOINCServer/cplan/
   HTML_OPS_URL = http://BOINCServer/cplan_ops/
        KEY_DIR = /home/boincadmin/projects/cplan/keys/
        DB_NAME = cplan
        DB_HOST = 

Delete /home/boincadmin/projects/cplan/? [y/N]  y
Deleting /home/boincadmin/projects/cplan/

Continue? [Y/n]  y
Creating directories
Generating encryption keys
Copying files
Setting up database
Traceback (most recent call last):
  File "./make_project", line 234, in <module>
    project.install_project()                                                     
  File "/home/boincadmin/boinc-src/py/Boinc/setup_project.py", line 592, in install_project                                                                         
    drop_first = options.drop_db_first                                            
  File "/home/boincadmin/boinc-src/py/Boinc/database.py", line 290, in create_database                                                                              
    _execute_sql_script(cursor, os.path.join(srcdir, 'db', file))                 
  File "/home/boincadmin/boinc-src/py/Boinc/database.py", line 277, in _execute_sql_script                                                                          
    cursor.execute(query)                                                         
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)                                           
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler                                                                   
    raise errorclass, errorvalue                                                  
_mysql_exceptions.OperationalError: (1072, "Key column 'md5' doesn't exist in table")

**Comment by davidpanderson** [comment]
This was fixed recently.
Pull the latest version and try again.
-- David
