### ISSUE TITLE
BOINC Manager crashes on recent distros

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#198]
**Reported by romw on 23 Dec 37386998 18:13 UTC**

```
Program received signal SIGSEGV, Segmentation fault.
[to Thread -1209026880 (LWP 3753)](Switching) 0x009a5300 in pthread_mutex_lock () from /lib/libpthread.so.0
(gdb) bt
#0  0x009a5300 in pthread_mutex_lock () from /lib/libpthread.so.0
#1  0x00ab2846 in pthread_mutex_lock () from /lib/libc.so.6
#2  0x00184acc in g_logv () from /usr/lib/libglib-2.0.so.0
#3  0x00184c79 in g_log () from /usr/lib/libglib-2.0.so.0
#4  0x00184d5b in g_return_if_fail_warning () from /usr/lib/libglib-2.0.so.0
#5  0x004eacd2 in gdk_window_set_title () from /usr/lib/libgdk-x11-2.0.so.0
#6  0x004ef9cf in gdk_window_new () from /usr/lib/libgdk-x11-2.0.so.0
#7  0x004ccf4d in gdk_display_open () from /usr/lib/libgdk-x11-2.0.so.0
#8  0x004abaef in gdk_display_open_default_libgtk_only ()
   from /usr/lib/libgdk-x11-2.0.so.0
#9  0x059e2bff in gtk_init_check () from /usr/lib/libgtk-x11-2.0.so.0 #10 0x082a7d5c in ?? ()
#11 0xbff7fe78 in ?? ()
#12 0xbff7fe7c in ?? ()
#13 0x088fdc70 in ?? ()
#14 0x00000000 in ?? ()
(gdb)                          

```

**Comment by romw** [comment]
**Commented by Nicolas on 28 Dec 37387915 07:33 UTC**
Fixed formatting.

What is this bug duplicate of? (ie. what's the other ticket number?)
