### ISSUE TITLE
scheduler error

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc#1994]
The scheduler appears to be broken by 20d07be. I get
```
Wed 26 Jul 2017 05:25:06 PM CEST | boincserver | [http] [ID#1] Received header from server: HTTP/1.1 500 Internal Server Error
```
on the client log and 
```
[Wed Jul 26 15:25:06.942611 2017] [cgi:error] [pid 22] [client 172.17.0.1:56098] End of script output before headers: cgi
```
on the server log when the client requests jobs. I believe this is a sign the scheduler is crashing. This doesn't happen if I use the commit right before 20d07be. 

This is holding me back from releasing a new version of boinc-server-docker which I would like to do to fix some recent Issues that have been brought up. That release will need https://github.com/BOINC/boinc/pull/1992, but which would otherwise be broken by 20d07be. 

CC: @davidpanderson

**Comment by marius311** [comment]
This is on a totally fresh build, so I don't think it's related to that. I just double-checked and the DB indeed does have the keywords field in it.

**Comment by davidpanderson** [comment]
Can you do the following:
copy a scheduler request file from the client to the cgi-bin dir, say req.xml
gdb cgi
r < req.xml
and send me the resulting stack trace.
-- D

**Comment by marius311** [comment]
Sure, here's the trace
```
(gdb) r < sched/140_0_sched_request.xml 
Starting program: /root/project/cgi-bin/cgi < sched/140_0_sched_request.xml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff40cc700 (LWP 315)]
[Thread 0x7ffff40cc700 (LWP 315) exited]

Program received signal SIGSEGV, Segmentation fault.
keyword_sched_remove_job (i=0) at sched_keyword.cpp:85
85	sched_keyword.cpp: No such file or directory.
(gdb) bt
#0  keyword_sched_remove_job (i=0) at sched_keyword.cpp:85
#1  0x000000000042764d in send_work_score_type (rt=rt@entry=0) at sched_score.cpp:331
#2  0x00000000004277fa in send_work_score () at sched_score.cpp:363
#3  0x000000000042ccb5 in send_work () at sched_send.cpp:1704
#4  0x000000000040f04d in process_request (
    code_sign_key=code_sign_key@entry=0x68c6f0 "1024\n9ddf861de12ebd56f3f3fd876fd18f4d81c508b9b7c954ce7ca09bc9b1c8d73b\n894251abcef747cfa88a913e5641a62a123de32fc07abd54294342fd65e51b0c\nbbed03bb84b52948193bfb0b8cea3016d80b00a18a6f0936ca4bd229a287e93a\n"...)
    at handle_request.cpp:1434
#5  0x000000000040ff48 in handle_request (fin=<optimized out>, fout=0x7ffff63d92a0 <_IO_2_1_stdout_>, 
    code_sign_key=0x68c6f0 "1024\n9ddf861de12ebd56f3f3fd876fd18f4d81c508b9b7c954ce7ca09bc9b1c8d73b\n894251abcef747cfa88a913e5641a62a123de32fc07abd54294342fd65e51b0c\nbbed03bb84b52948193bfb0b8cea3016d80b00a18a6f0936ca4bd229a287e93a\n"...)
    at handle_request.cpp:1514
#6  0x0000000000405c97 in main (argc=0, argv=0x0) at sched_main.cpp:665
(gdb) 
```

and the [request](https://gist.github.com/marius311/e6813006cedb93e872f5d176a66ee340).

**Comment by davidpanderson** [comment]
Thanks.  I checked in a fix.

**Comment by marius311** [comment]
Thanks for the quick attention, I confirm it fixed it.
