### ISSUE TITLE
user-reported Android issue

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2211]
This is what happens when I try to run bonic on my Asus ZenFone 2 - please fix!

GUI Messages

```
11-04 09:21:51.625 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:51.625 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:51.625 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:51.625 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:51.625 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:51.625 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:51.625 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:51.625 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:51.625 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:51.625 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:51.625 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:51.625 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:51.625 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:51.625 E/BOINC_GUI(17156): IOException
11-04 09:21:51.610 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:50.621 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:50.621 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:50.621 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:50.621 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:50.621 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:50.621 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:50.621 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:50.621 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:50.621 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:50.621 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:50.621 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:50.621 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:50.621 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:50.621 E/BOINC_GUI(17156): IOException
11-04 09:21:50.608 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:49.641 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:49.641 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:49.641 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:49.641 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:49.641 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:49.641 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:49.641 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:49.641 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:49.641 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:49.641 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:49.641 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:49.641 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:49.641 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:49.641 E/BOINC_GUI(17156): IOException
11-04 09:21:49.623 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:48.674 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:48.674 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:48.674 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:48.674 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:48.674 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:48.674 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:48.674 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:48.674 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:48.674 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:48.674 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:48.674 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:48.674 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:48.674 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:48.674 E/BOINC_GUI(17156): IOException
11-04 09:21:48.657 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:47.613 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:47.613 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:47.613 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:47.613 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:47.613 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:47.613 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:47.613 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:47.613 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:47.613 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:47.613 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:47.613 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:47.613 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:47.613 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:47.613 E/BOINC_GUI(17156): IOException
11-04 09:21:47.600 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:46.596 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:46.596 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:46.596 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:46.596 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:46.596 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:46.596 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:46.596 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:46.596 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:46.596 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:46.596 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:46.596 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:46.596 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:46.596 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:46.596 E/BOINC_GUI(17156): IOException
11-04 09:21:46.581 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:45.627 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:45.627 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:45.627 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:45.627 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:45.627 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:45.627 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:45.627 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:45.627 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:45.627 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:45.627 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:45.627 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:45.627 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:45.627 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:45.627 E/BOINC_GUI(17156): IOException
11-04 09:21:45.612 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:44.612 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:44.612 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:44.612 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:44.612 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:44.612 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:44.612 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:44.612 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:44.612 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:44.612 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:44.612 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:44.612 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:44.612 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:44.612 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:44.612 E/BOINC_GUI(17156): IOException
11-04 09:21:44.596 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:43.636 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:43.636 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:43.636 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:43.636 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:43.636 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:43.636 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:43.636 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:43.636 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:43.636 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:43.636 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:43.636 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:43.636 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:43.636 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:43.636 E/BOINC_GUI(17156): IOException
11-04 09:21:43.616 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:42.610 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:42.610 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:42.610 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:42.610 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:42.610 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:42.610 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:42.610 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:42.610 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:42.610 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:42.610 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:42.610 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:42.610 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:42.610 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:42.610 E/BOINC_GUI(17156): IOException
11-04 09:21:42.596 W/BOINC_GUI(17156): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
11-04 09:21:41.584 E/BOINC_GUI(17156): ... 7 more
11-04 09:21:41.584 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:209)
11-04 09:21:41.584 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(Native Method)
11-04 09:21:41.584 E/BOINC_GUI(17156): Caused by: java.io.IOException: No such file or directory
11-04 09:21:41.584 E/BOINC_GUI(17156): at java.util.Timer$TimerImpl.run(Timer.java:284)
11-04 09:21:41.584 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:340)
11-04 09:21:41.584 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.access$5(Monitor.java:349)
11-04 09:21:41.584 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:352)
11-04 09:21:41.584 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:525)
11-04 09:21:41.584 E/BOINC_GUI(17156): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:594)
11-04 09:21:41.584 E/BOINC_GUI(17156): at java.lang.Runtime.exec(Runtime.java:173)
11-04 09:21:41.584 E/BOINC_GUI(17156): at java.lang.ProcessManager.exec(ProcessManager.java:211)
11-04 09:21:41.584 E/BOINC_GUI(17156): java.io.IOException: Error running exec(). Command: [/data/data/edu.berkeley.boinc/client/boinc, --daemon, --gui_rpc_unix_domain] Working Directory: /data/data/edu.berkeley.boinc/client Environment: null
11-04 09:21:41.584 E/BOINC_GUI(17156): IOException

```

**Comment by davidpanderson** [comment]
Another user says:

Bugs
1. Sometimes project cannot be added because there is no option to select project
2. Sometimes boinc doesnt open, i have to force stop then it opens.

**Comment by AenBleidd** [comment]
Addition to point 2:
if there is no access no Internet BOINC application hangs on spoash screen

Best regards,
Vitalii

Sent via Android

11 янв. 2018 г. 8:55 пользователь "David Anderson" <notifications@github.com>
написал:

**Comment by adamradocz** [comment]
I have the same issue as point 1.

**Comment by adamradocz** [comment]
I think this issue can be closed. I haven't seen the point 1 since the new version.
There's no version info and no OS info.

**Comment by AenBleidd** [comment]
The original issue that is shown with the log file is still happens if BOINC client was killed by OS core and user tries to reopen BOINC Manager without complete application shutdown. So I'd keep this to fix later

**Comment by 2tbc1887** [comment]
@brevilo I saw you were asking about the original author, I believe it was actually me who sent this in as I did from a zenfone 2 and included these logs. I'm happy to answer any questions / run any tests on the phone as it still works

**Comment by AenBleidd** [comment]
@2tbc1887, could you please test it with the latest version from here:
https://boinc.berkeley.edu/dl/boinc_7.16.16.apk
?

**Comment by 2tbc1887** [comment]
@AenBleidd Will do asap

**Comment by 2tbc1887** [comment]
@AenBleidd, looks fixed, can't test running a project tho cause nothing is supporting x86 android (I was able to manually add though)

**Comment by AenBleidd** [comment]
@2tbc1887, thanks you for verification!
