### ISSUE TITLE
Client does not auto-start on Android 8

### ISSUE THREAD

**Issue by IzzySoft** [BOINC/boinc#4237]
**Describe the bug**
I have the BOINC client set to automatically start, still it does not e.g. after a reboot. Starting it manually it then complains to be already running (same happens e.g. right after install with the first start).

**Steps To Reproduce**
1. Install BOINC
2. Start Client

Or:

1. Reboot the device with the BOINC Client already installed (and set to auto-start)
2. seeing the service not running, start the app.

**Expected behavior**
* app is started automatically when set to
* app does not complain another instance would be running already if there clearly is none

**Screenshots**
n/a, but: <details><summary>Logcat</summary><pre><code>5524  5524 E AndroidRuntime: FATAL EXCEPTION: main
5524  5524 E AndroidRuntime: Process: edu.berkeley.boinc, PID: 5524
5524  5524 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver edu.berkeley.boinc.receiver.BootReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=edu.berkeley.boinc/.client.Monitor }: app is in background uid UidRecord{d0bf8d9 u0a121 RCVR idle change:uncached procs:1 seq(0,0,0)}
5524  5524 E AndroidRuntime:    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
5524  5524 E AndroidRuntime:    at android.app.ActivityThread.-wrap17(Unknown Source:0)
5524  5524 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
5524  5524 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:106)
5524  5524 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:164)
5524  5524 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6494)
5524  5524 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
5524  5524 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
5524  5524 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
5524  5524 E AndroidRuntime:    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
5524  5524 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=edu.berkeley.boinc/.client.Monitor }: app is in background uid UidRecord{d0bf8d9 u0a121 RCVR idle change:uncached procs:1 seq(0,0,0)}
5524  5524 E AndroidRuntime:    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
5524  5524 E AndroidRuntime:    at android.app.ContextImpl.startService(ContextImpl.java:1477)
5524  5524 E AndroidRuntime:    at android.content.ContextWrapper.startService(ContextWrapper.java:650)
5524  5524 E AndroidRuntime:    at android.content.ContextWrapper.startService(ContextWrapper.java:650)
5524  5524 E AndroidRuntime:    at edu.berkeley.boinc.receiver.BootReceiver.onReceive(Unknown Source:51)
5524  5524 E AndroidRuntime:    at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
5524  5524 E AndroidRuntime:    ... 9 more
</code></pre></details>

**System Information**
 - OS: Android 8.1 (LineageOS 15)
 - BOINC Version: 7.16.16

**Additional context**
Probably related: [Background Execution Limits | Android Developers](https://developer.android.com/about/versions/oreo/background)

> With Android 8.0, there is a complication; the system doesn't allow a background app to create a background service. For this reason, Android 8.0 introduces the new method startForegroundService () to start a new service in the foreground.

I've also found issues in other projects stating "Background start not allowed when Optimizing battery use", so I now excempted BOINC from that and will keep an eye on it.

**Comment by IzzySoft** [comment]
Just to confirm: exempting BOINC from battery optimization did the trick. Right after the reboot, service was running automatically and could be accessed via its notification.

Still wonder why it doesn't upload completed tasks (2 of them on the device already, 2 more running, 1 stuck at "downloading"). It was able to download them before, and the other client ships them immediately. No idea where to look for logs. Enabled some in the settings, and after the boot (not before) some showed up in logcat, not sure where they belong:

<details><summary>Logcat</summary><pre><code>
5737  5794 W BOINC_GUI: Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
5737  5794 W BOINC_GUI: connect failure: IO
5737  5794 W BOINC_GUI: java.io.IOException: Connection refused
5737  5794 W BOINC_GUI:     at android.net.LocalSocketImpl.connectLocal(Native Method)
5737  5794 W BOINC_GUI:     at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
5737  5794 W BOINC_GUI:     at android.net.LocalSocket.connect(LocalSocket.java:145)
5737  5794 W BOINC_GUI:     at edu.berkeley.boinc.m.q0.z(Unknown Source:35)
5737  5794 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor.j(Unknown Source:11)
5737  5794 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor.h(Unknown Source:287)
5737  5794 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor.I(Unknown Source:14)
5737  5794 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor.g(Unknown Source:0)
5737  5794 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor$a.run(Unknown Source:2)
5737  5794 W BOINC_GUI:     at java.util.TimerThread.mainLoop(Timer.java:555)
5737  5794 W BOINC_GUI:     at java.util.TimerThread.run(Timer.java:505)
5737  5794 E BOINC_GUI: Connection failed!
</code></pre></details>

The block (except for the first 2 lines) is repeated 3 times, which would correspond to the number of pending up/downloads (coincidence?). It doesn't mention where it connects to or what connection was refused (or if it even was a network connection), so it's hard to check. Despite of having `http_debug` enabled as well, all I see is `BOINC_GUI` messages, so it's probably not that. Going via *projects › (tap project) › update / repeat* doesn't help. But websites (here: Rosetta and Universe) state the client has connected.

Further, though probably unrelated, a null-pointer exception shows up in the logs:

<details><summary>Logcat</summary><pre><code>
5721  5721 E BOINC_GUI: NoticesFragment.onResume error:
5721  5721 E BOINC_GUI: java.lang.NullPointerException
5721  5721 E BOINC_GUI:     at edu.berkeley.boinc.c.G0(Unknown Source:26)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.Fragment.f1(Unknown Source:17)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.r.m(Unknown Source:33)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.m.C0(Unknown Source:253)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.m.B0(Unknown Source:2)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.m.z0(Unknown Source:58)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.m.A0(Unknown Source:47)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.m.J(Unknown Source:9)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.m.H(Unknown Source:6)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.h.p(Unknown Source:4)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.d.w(Unknown Source:9)
5721  5721 E BOINC_GUI:     at androidx.fragment.app.d.onPostResume(Unknown Source:3)
5721  5721 E BOINC_GUI:     at androidx.appcompat.app.e.onPostResume(Unknown Source:0)
5721  5721 E BOINC_GUI:     at android.app.Activity.performResume(Activity.java:7141)
5721  5721 E BOINC_GUI:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
5721  5721 E BOINC_GUI:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
5721  5721 E BOINC_GUI:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
5721  5721 E BOINC_GUI:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
5721  5721 E BOINC_GUI:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
5721  5721 E BOINC_GUI:     at android.os.Handler.dispatchMessage(Handler.java:106)
5721  5721 E BOINC_GUI:     at android.os.Looper.loop(Looper.java:164)
5721  5721 E BOINC_GUI:     at android.app.ActivityThread.main(ActivityThread.java:6494)
5721  5721 E BOINC_GUI:     at java.lang.reflect.Method.invoke(Native Method)
5721  5721 E BOINC_GUI:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
5721  5721 E BOINC_GUI:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
</code></pre></details>

Apologies should I have mixed up multiple issues here (probably the upload issue), but I wasn't sure what might be related. On a side note, the first F-Droid test build still runs fine on my test device. I consider uninstalling the final build and retrying the test build on this device as well – if there is any way to save the tasks that failed uploading (ideally even to backup/restore that so I could maybe try on a third device)…

<details><summary>Screenshots</summary>
<a href="https://user-images.githubusercontent.com/6781438/109726398-fb925b00-7bb2-11eb-9f92-763a173ef85c.jpg" title="projects"><img src="https://user-images.githubusercontent.com/6781438/109726398-fb925b00-7bb2-11eb-9f92-763a173ef85c.jpg" width="200" alt="projects"></a> <a href="https://user-images.githubusercontent.com/6781438/109726400-fcc38800-7bb2-11eb-9d61-808cce6b1495.jpg" title="tasks"><img src="https://user-images.githubusercontent.com/6781438/109726400-fcc38800-7bb2-11eb-9d61-808cce6b1495.jpg" width="200" alt="tasks"></a> <a href="https://user-images.githubusercontent.com/6781438/109726401-fcc38800-7bb2-11eb-9f11-409a82937762.jpg" title="log settings"><img src="https://user-images.githubusercontent.com/6781438/109726401-fcc38800-7bb2-11eb-9f11-409a82937762.jpg" width="200" alt="log settings"></a>
</details>
