### ISSUE TITLE
Even more PHP 8 deprecation warnings/errors

### ISSUE THREAD

**Issue by gchilders** [BOINC/boinc#4776]
Thanks for cleaning these up so quickly! I'm seeing two more persist, and one that I didn't catch earlier:

home.php:

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, stdClass given in /home/boincadm/projects/nfs/html/inc/user.inc:118 Stack trace: #0 /home/boincadm/projects/nfs/html/inc/user.inc(563): show_other_projects() #1 /home/boincadm/projects/nfs/html/inc/bootstrap.inc(263): {closure}() #2 /home/boincadm/projects/nfs/html/inc/user.inc(574): grid() #3 /home/boincadm/projects/nfs/html/user/home.php(52): show_account_private() #4 {main} thrown in /home/boincadm/projects/nfs/html/inc/user.inc on line 118

cert_all.php:

Warning: Attempt to read property "total_credit" on string in /home/boincadm/projects/nfs/html/user/cert_all.php on line 48 (lots of these)
Warning: Undefined property: stdClass::$total_credit in /home/boincadm/projects/nfs/html/user/cert_all.php on line 48
Warning: Attempt to read property "total_credit" on string in /home/boincadm/projects/nfs/html/user/cert_all.php on line 83 (lots of these)

prefs_edit.php?subset=project

Deprecated: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in /home/boincadm/projects/nfs/html/inc/util.inc on line 1047

**Comment by gchilders** [comment]
Those changes to user.inc lead to the following error in home.php:

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, stdClass given in /home/boincadm/projects/nfs/html/inc/user.inc:82 Stack trace: #0 /home/boincadm/projects/nfs/html/user/home.php(30): get_other_projects() #1 {main} thrown in /home/boincadm/projects/nfs/html/inc/user.inc on line 82

**Comment by gchilders** [comment]
Also add 
if (!$x) return $x;
to sanitize_tags() on line 1027 of util.inc.
