### ISSUE TITLE
PHP 8 deprecation warnings/errors in periodic tasks

### ISSUE THREAD

**Issue by gchilders** [BOINC/boinc#4779]
Thanks again for the quick work on these. The web pages look good now as far as I see. Turning to the periodic tasks, I see two with issues:

delete_spammers.php:
Deprecated: Function strftime() is deprecated in /home/boincadm/projects/nfs/html/ops/delete_spammers.php on line 464

team_import.php:
Deprecated:  html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated in /home/boincadm/projects/nfs/html/ops/team_import.php on line 51
Processing BOINC Synergy <redacted>@gmail.com
   case 1
   updating
PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect string value: '\xE2\xAD\x90\xE2\xAD\x90...' for column 'description' at row 1 in /home/boincadm/projects/nfs/html/inc/db_conn.inc:69
Stack trace:
#0 /home/boincadm/projects/nfs/html/inc/db_conn.inc(69): mysqli->query()
#1 /home/boincadm/projects/nfs/html/inc/db_conn.inc(176): DbConn->do_query()
#2 /home/boincadm/projects/nfs/html/inc/boinc_db.inc(262): DbConn->update()
#3 /home/boincadm/projects/nfs/html/ops/team_import.php(124): BoincTeam->update()
#4 /home/boincadm/projects/nfs/html/ops/team_import.php(247): update_team()
#5 /home/boincadm/projects/nfs/html/ops/team_import.php(284): handle_team()
#6 /home/boincadm/projects/nfs/html/ops/team_import.php(291): main()
#7 {main}
  thrown in /home/boincadm/projects/nfs/html/inc/db_conn.inc on line 69

**Comment by davidpanderson** [comment]
The "description" field of one of the BOINC-wide teams (BOINC Synergy) contained what looked like garbage characters.  I cleaned these up; please try team_import.php again

**Comment by gchilders** [comment]
Got further, but here's an issue with SETI@Taiwan:

Deprecated: html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated in /home/boincadm/projects/nfs/html/ops/team_import.php on line 51
Processing SETI@Taiwan �x�W�&zeta;� redacted@gmail.com
PHP Fatal error:  Uncaught mysqli_sql_exception: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,COERCIBLE) for operation '=' in /home/boincadm/projects/nfs/html/inc/db_conn.inc:69
Stack trace:
#0 /home/boincadm/projects/nfs/html/inc/db_conn.inc(69): mysqli->query()
#1 /home/boincadm/projects/nfs/html/inc/db_conn.inc(116): DbConn->do_query()
#2 /home/boincadm/projects/nfs/html/inc/db_conn.inc(131): DbConn->lookup_fields()
#3 /home/boincadm/projects/nfs/html/inc/boinc_db.inc(270): DbConn->lookup()
#4 /home/boincadm/projects/nfs/html/inc/boinc_db.inc(275): BoincTeam::lookup()
#5 /home/boincadm/projects/nfs/html/ops/team_import.php(234): BoincTeam::lookup_name()
#6 /home/boincadm/projects/nfs/html/ops/team_import.php(284): handle_team()
#7 /home/boincadm/projects/nfs/html/ops/team_import.php(291): main()
#8 {main}
  thrown in /home/boincadm/projects/nfs/html/inc/db_conn.inc on line 69

**Comment by davidpanderson** [comment]
I fixed the first warning.

The MYSQL problem is outside of my expertise; maybe someone else can figure it out.

**Comment by AenBleidd** [comment]
This looks similar to this issue: https://github.com/BOINC/boinc/issues/1503

**Comment by gchilders** [comment]
I think there's a larger underlying issue with the collation used in the database, but for now to circumvent the issue I changed boinc_db.inc line 275 to
        return self::lookup("name='$name' COLLATE utf8mb4_0900_ai_ci");

This gets me to
Processing Centro Meteorologico Lombardo - Italy redacted@email
   case 1
   updating
PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect string value: '\xE8\xA0\xB5na ...' for column 'description' at row 1 in /home/boincadm/projects/nfs/html/inc/db_conn.inc:69

Another team with garbage characters?

**Comment by davidpanderson** [comment]
The XML file (boinc_teams.xml) is valid UTF-8, according to iconv:
https://stackoverflow.com/questions/115210/how-to-check-whether-a-file-is-valid-utf-8
(although it probably contains lots of wrong characters because of earlier encoding issues.

So the problem is probably that your DB uses the latin1 encoding,
and can't store certain UTF-8 characters.
Perhaps the 8.1 version of mysqli is the first version that checks this.

If this is the case, the likely solution is to convert the database
(at least the fields that hold user-supplied data) to utf8mb4.
I tried doing this on a test project and immediately ran into problems.
I don't have time to follow through on this.
It's not super important since BOINC-wide teams don't change much.

**Comment by gchilders** [comment]
First, I had to use 

SET SQL_MODE='ALLOW_INVALID_DATES';

since mysql doesn't like dates to be 0.  After that I did

alter table team modify column name varchar(254) character set utf8 collate utf8_unicode_520_ci, modify column description text character set utf8 collate utf8_unicode_520_ci;

I couldn't use utf8mb4 because that resulted in a key length of over 1000 bytes, which isn't allowed apparently. After that I got a little further, but still got stuck on

Processing SETI.KHERSON redacted@email
   case 1
   updating
PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect string value: '\xF0\xB1\xAE\xAD\xF1\xAA...' for column 'description' at row 1 in /home/boincadm/projects/nfs/html/inc/db_conn.inc:69

**Comment by davidpanderson** [comment]
Seems to me the long-term solution is to change all fields with user-supplied text (some fields of the user and team tables, forum stuff, maybe others) to utf8mb4.  This may require shortening some of these fields (to 250 chars?) because of the 1000 byte key limit.

**Comment by FraSanga** [comment]
The team_import.php crash here has a specific root cause: handle_team() (called from main()'s per-team loop) has no try/catch around it at all, so any uncaught exception during processing — a duplicate-key collision, an encoding issue like the one in this report, or anything else a single team's data can trigger — kills the entire run mid-list. Every team after the failing one silently never gets processed, and since most collisions/data issues recur identically on every subsequent run, the import can get stuck at the exact same point forever.

Confirmed this independently via a different trigger: two real official teams whose placeholder founder both had the display name "Coordinador" hit user.name's unique constraint, throwing the same uncaught mysqli_sql_exception shown in this report's own stack trace (just via BoincUser::insert() in make_user() rather than BoincTeam::update()).

Fix: wrap each team's handle_team() call in try/catch so one team's failure becomes an isolated, logged skip instead of a total outage — every other team still gets processed. Tested against a deliberately crafted collision fixture: the unpatched script reproduces the exact crash-and-stop behavior; the patched version logs the failure and continues to the next team.

Happy to open a PR for this fix.

---

*This diagnosis and fix were prepared with AI assistance (Claude Sonnet 5). Verified against the actual BOINC source and reproduced live against a running test deployment. Any resulting PR will include the required `Assisted-by:` trailer per the BOINC AI Assistants Usage Policy.*

**Comment by AenBleidd** [comment]
@FraSanga, please go ahead and make a PR

**Comment by FraSanga** [comment]
Checked everything in this issue against current `master`:

- **`delete_spammers.php` `strftime()`** — fixed in `5fae50505` (2022-06); both calls are now `date(DATE_RFC2822)`, no `strftime` left in the file.
- **`team_import.php:51` `html_entity_decode()` passing null** — fixed by the simplexml rewrite in `d089d8c7d`; `decode()` returns early on a falsy arg and every caller passes a `(string)`-cast value.
- **`team_import.php` `mysqli_sql_exception: Incorrect string value … for column 'description'`** — the root cause (user-text columns not being `utf8mb4` on older DBs) is addressed by `html/ops/db_update.php::update_5_2_2026a` / `update_5_2_2026b`, which shorten the index-bearing columns to `utf8mb4`-safe lengths and `CONVERT TO CHARACTER SET utf8mb4` across all tables. `db/schema.sql` carries the shortened lengths for fresh installs, and `db_conn.inc` sets the connection charset to `utf8mb4`. On top of that, #7301 (merged) makes any remaining single-team failure a logged skip instead of aborting the whole run.

All three reported problems are resolved on current `master` — suggest closing.

---

*Prepared with AI assistance (Claude Sonnet 5), verified against the current BOINC source. Per the BOINC AI Assistants Usage Policy — this comment is analysis only; no code change is proposed.*

**Comment by AenBleidd** [comment]
Thank you!
