### ISSUE TITLE
config.xml error

### ISSUE THREAD

**Issue by leepeter2019** [BOINC/boinc#5499]
i run "install_fitcrack.sh"
it generated error 'there is no config.xml' file
any help?

cp: cannot stat 'boinc/sched/work_generator': No such file or directory
cp: cannot stat 'boinc/sched/assimilator': No such file or directory
cp: cannot stat 'boinc/sched/bitwise_validator': No such file or directory
cp: cannot stat 'boinc/sched/trickler': No such file or directory
Starting Fitcrack server again...
filename: config.xml
Traceback (most recent call last):
  File "/home/boincadm/projects/fitcrack/py/Boinc/boincxml.py", line 128, in read
    self.xml = xml.dom.minidom.parse(self.filename)
  File "/usr/local/lib/python3.9/xml/dom/minidom.py", line 1988, in parse
    return expatbuilder.parse(file)
  File "/usr/local/lib/python3.9/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'config.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boincadm/projects/fitcrack/./bin/start", line 757, in <module>
    config = configxml.ConfigFile(config_filename).read()
  File "/home/boincadm/projects/fitcrack/py/Boinc/boincxml.py", line 132, in read
    raise Exception("Couldn't parse XML config\n")
Exception: Couldn't parse XML config

filename: config.xml
Traceback (most recent call last):
  File "/home/boincadm/projects/fitcrack/py/Boinc/boincxml.py", line 128, in read
    self.xml = xml.dom.minidom.parse(self.filename)
  File "/usr/local/lib/python3.9/xml/dom/minidom.py", line 1988, in parse
    return expatbuilder.parse(file)
  File "/usr/local/lib/python3.9/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'config.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boincadm/projects/fitcrack/./bin/status", line 757, in <module>
    config = configxml.ConfigFile(config_filename).read()
  File "/home/boincadm/projects/fitcrack/py/Boinc/boincxml.py", line 132, in read
    raise Exception("Couldn't parse XML config\n")
Exception: Couldn't parse XML config

**Comment by AenBleidd** [comment]
Please follow this documentation: https://github.com/BOINC/boinc/wiki/Computing-with-boinc
