### ISSUE TITLE
Android app v8.0.2 : crash when editing GUI auth key on device with no auth

### ISSUE THREAD

**Issue by rwaldura** [BOINC/boinc#5802]
**Describe the bug**
App crashes when editing the GUI auth key on device with no protection. 
[8.0.0 release notes](https://github.com/BOINC/boinc/wiki/Client-release-notes#changes-in-800) mention: 
_Use device protection (fingerprint, face ID) when show or edit password._

**Steps To Reproduce**
1. Do not setup any on-device auth: no fingerprint, no PIN. 
1. Install BOINC client 8.0.2 to Android phone. 
2. Open BOINC app, go to Preferences, tap the "GUI Authenication Key" field.
1. App crashes with: ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.BIOMETRIC_ENROLL } 

**Expected behavior**
App does not crash; I can edit the key. 

**System Information**
 - OS: 
WW_Phone-user 8.0.0 OPR1.170623.032 15.0610.1909.39-0 release-keys
gms versionName=24.33.33 (040400-666381490)
 - BOINC Version: 8.0.2

**Additional context**
```
09-09 15:51:04.723  1635  7040 I ActivityManager: START u0 {act=android.settings.BIOMETRIC_ENROLL (has extras)} from uid 10043
09-09 15:51:04.724  8570  8570 D AndroidRuntime: Shutting down VM
09-09 15:51:04.725  8570  8570 E AndroidRuntime: FATAL EXCEPTION: main
09-09 15:51:04.725  8570  8570 E AndroidRuntime: Process: edu.berkeley.boinc, PID: 8570
09-09 15:51:04.725  8570  8570 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.BIOMETRIC_ENROLL (has extras) }
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1943)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1617)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4513)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile:2)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.core.app.b$b.b(Unknown Source:0)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.core.app.b.p(Unknown Source:0)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.activity.ComponentActivity$b.f(Unknown Source:160)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.activity.result.e$a.b(Unknown Source:31)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.activity.result.c.a(Unknown Source:1)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.fragment.app.w.V0(Unknown Source:27)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.fragment.app.Fragment.O1(Unknown Source:8)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.fragment.app.Fragment.N1(Unknown Source:1)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at t2.k0.u2(Unknown Source:50)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at t2.k0.i2(Unknown Source:0)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at t2.h0.a(Unknown Source:6)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.preference.Preference.a0(Unknown Source:20)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.preference.Preference.b0(Unknown Source:0)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at androidx.preference.Preference$a.onClick(Unknown Source:2)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.view.View.performClick(View.java:6256)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24717)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:169)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6585)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-09 15:51:04.725  8570  8570 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
09-09 15:51:04.728  1635  7040 W ActivityManager:   Force finishing activity edu.berkeley.boinc/.BOINCActivity

```

**Comment by rwaldura** [comment]
Maybe related to #4236?

**Comment by rwaldura** [comment]
When I set a "lock screen" (pattern), I can edit the field.
Remove the lock screen, and the app crashes.

**Comment by rwaldura** [comment]
Device where I found the bug is running Android 8, API level 26.

[StackOverflow](https://stackoverflow.com/questions/65785998/no-activity-found-to-handle-intent-act-android-settings-biometric-enroll-has) says:
["ACTION_BIOMETRIC_ENROLL"](https://developer.android.com/reference/android/provider/Settings#ACTION_BIOMETRIC_ENROLL) added at API 30.

BOINC app v8.0.2 appears to target API level 16 at a minimum, so a fix would be nice! Thanks. 
` <uses-sdk       minSdkVersion='16'       targetSdkVersion='28'>`
